### PR TITLE
Update release process

### PR DESCRIPTION
**Pull request by getlarge**
In order to keep track of historical changes of the schema, i'm proposing the following changes : 
- remove the version from file names
- create a helper script that will update the schemas $id based on a version number (using semver format)
- use [release-it](https://github.com/release-it/release-it) to associate a release with a tag on github, so that we can access easily different versions of a schema from its tag 
- the schema can be accessed remotely with that url pattern `https://raw.githubusercontent.com/s1seven/schemas/${version}/${schemaName}.schema.json`

### CODE REVIEW

**Comment by stiebitzhofer** [comment]
1. Happy with removing version number from the file name.
2. Happy with schemver.
3. release-it looks good. We have to think about a more formal release process for the future (I want to suggest this to other projects like e-CoC.org too). 
4. Is it possible to have an URL that does not include Github? As you have seen something like
`https://schemas.en10204.io/${version}/${schemaName}.schema.json`

**Comment by getlarge** [comment]
3 - What do you mean by formal process ?

4 - we could but i don't know how files from this github repo are deployed, is there a place where that process is described ?

**Comment by getlarge** [comment]
@stiebitzhofer Ok to merge it ?

**Comment by getlarge** [comment]
@stiebitzhofer  Why did you close it ?

**Pull request merged**
